import type { PropertyDTO } from "../types/property.js"

// Hardcoded sample properties for local development and testing.
// Shapes are identical to what DomainPropertyProvider produces.
export const mockProperties: PropertyDTO[] = [
  {
    externalId: "mock-1",
    source: "mock",
    address: "12 Example Street, Brisbane",
    suburb: "Brisbane",
    state: "QLD",
    postcode: "4000",
    price: 650000,
    displayPrice: "$650,000",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "House",
    latitude: -27.4698,
    longitude: 153.0251,
    description: "A lovely modern house close to the city centre.",
    listingUrl: "https://example.com/mock-1",
    openHouses: [
      {
        externalId: "mock-1-0",
        startDatetime: new Date("2026-10-18T10:00:00"),
        endDatetime: new Date("2026-10-18T10:30:00"),
        status: "SCHEDULED",
      },
    ],
  },
  {
    externalId: "mock-2",
    source: "mock",
    address: "45 Sample Avenue, South Brisbane",
    suburb: "South Brisbane",
    state: "QLD",
    postcode: "4101",
    price: 480000,
    displayPrice: "$480,000",
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: -27.4818,
    longitude: 153.0171,
    description: "Cosy apartment with river views.",
    listingUrl: "https://example.com/mock-2",
    openHouses: [
      {
        externalId: "mock-2-0",
        startDatetime: new Date("2026-10-19T11:00:00"),
        endDatetime: new Date("2026-10-19T11:30:00"),
        status: "SCHEDULED",
      },
      {
        externalId: "mock-2-1",
        startDatetime: new Date("2026-10-25T13:00:00"),
        endDatetime: new Date("2026-10-25T13:30:00"),
        status: "SCHEDULED",
      },
    ],
  },
  {
    externalId: "mock-3",
    source: "mock",
    address: "7 Test Court, New Farm",
    suburb: "New Farm",
    state: "QLD",
    postcode: "4005",
    price: null,
    displayPrice: "Auction",
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "House",
    latitude: -27.4654,
    longitude: 153.0509,
    description: "Spacious family home, auction coming up soon.",
    listingUrl: "https://example.com/mock-3",
    openHouses: [],
  },
  {
    externalId: "mock-4",
    source: "mock",
    address: "88 Placeholder Road, West End",
    suburb: "West End",
    state: "QLD",
    postcode: "4101",
    price: 1200000,
    displayPrice: "$1,200,000",
    bedrooms: 5,
    bathrooms: 3,
    propertyType: "House",
    latitude: -27.4823,
    longitude: 153.0088,
    description: "Luxury family home with pool.",
    listingUrl: "https://example.com/mock-4",
    openHouses: [
      {
        externalId: "mock-4-0",
        startDatetime: new Date("2026-10-18T14:00:00"),
        endDatetime: new Date("2026-10-18T14:30:00"),
        status: "SCHEDULED",
      },
    ],
  },
  {
    externalId: "mock-5",
    source: "mock",
    address: "3 Fixture Lane, Fortitude Valley",
    suburb: "Fortitude Valley",
    state: "QLD",
    postcode: "4006",
    price: 350000,
    displayPrice: "$350,000",
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: -27.4560,
    longitude: 153.0344,
    description: "Compact studio apartment, perfect for first home buyers.",
    listingUrl: "https://example.com/mock-5",
    openHouses: [],
  },
]